### ISSUE TITLE
"Headers already sent" error 

### ISSUE THREAD

**Issue by ax2000** [webtoolbox/craftcms-plugin#11]
Hi there,

I'm getting the error below when saving plugin form details from the Control Panel:

`An Error occurred while handling another error:
yii\web\HeadersAlreadySentException: Headers already sent in /app/craftcms/vendor/websitetoolbox/websitetoolboxcommunity/src/Websitetoolboxcommunity.php on line 95. in /app/craftcms/vendor/yiisoft/yii2/web/Response.php:369
Stack trace:
#0 /app/craftcms/vendor/yiisoft/yii2/web/Response.php(342): yii\web\Response->sendHeaders()
#1 /app/craftcms/vendor/yiisoft/yii2/web/ErrorHandler.php(136): yii\web\Response->send()
#2 /app/craftcms/vendor/craftcms/cms/src/web/ErrorHandler.php(192): yii\web\ErrorHandler->renderException(Object(yii\base\ErrorException))
#3 /app/craftcms/vendor/yiisoft/yii2/base/ErrorHandler.php(152): craft\web\ErrorHandler->renderException(Object(yii\base\ErrorException))
#4 /app/craftcms/vendor/craftcms/cms/src/web/ErrorHandler.php(66): yii\base\ErrorHandler->handleException(Object(yii\base\ErrorException))
#5 [internal function]: craft\web\ErrorHandler->handleException(Object(yii\base\ErrorException))
#6 {main}
Previous exception:
yii\base\ErrorException: Cannot modify header information - headers already sent by (output started at /app/craftcms/vendor/websitetoolbox/websitetoolboxcommunity/src/Websitetoolboxcommunity.php:95) in /app/craftcms/vendor/websitetoolbox/websitetoolboxcommunity/src/services/Sso.php:169
Stack trace:
#0 {main}`

I'm using `Craft CMS 4.8.1` and `Website Toolbox Community 2.0.3`.

Please let me know if you are able to replicate or if you'd need me to provide more details.

**Comment by webtoolbox** [comment]
Thank you for reporting the issue. We are investigating it and will update you as soon as possible.

**Comment by webtoolbox** [comment]
Hi Alberto. I'm glad to inform you that we were able to reproduce and fix the issue. The changes are now in Quality Assurance testing. Once it's tested within the next few days, we'll publish the changes to the repository.

**Comment by webtoolbox** [comment]
Hi Alberto. Thanks for your patience while we worked on fixing this issue.

We have made changes to fix the issue in the latest plugin release. To update to the latest version, please follow these steps:

1. Log in to your website's admin control panel.
2. Go to Utilities -> Updates
3. Locate the Website Toolbox Community plugin and click the update button.

Once you've updated the plugin, please confirm and let us know if the issue has been resolved.
