### ISSUE TITLE
Websitetoolbox stopping craft commerce sending emails?

### ISSUE THREAD

**Issue by ax2000** [webtoolbox/craftcms-plugin#12]
Hi there,

I had an issue with Craft Commerce not sending emails after an order was created. 

The error I was getting was `Session does not exist in a console request.`.  I initially thought the issue was within the email template but after a solid debugging session I saw that the emails were being sent when disabling the WebsiteToolBox plugin.

I think the error comes from the line 121 in `Websitetoolboxcommunity.php` using the `EVENT_BEFORE_RENDER_TEMPLATE` event. I wrapped that event code within a `if(!Craft::$app->getRequest()->getIsConsoleRequest()) ` statement and that seemed to do the job.

Currently I applied that fix in my environment and it seems working ok, but please note that I'm not a backend developer so take the above code with a grain of salt as I'm not sure if that would be the right way of doing things on Craft or if it would break the plugin logic.

Cheers,
Alberto

**Comment by webtoolbox** [comment]
Hi Alberto. Thank you for reporting the issue. We are investigating it and will update you as soon as possible.

**Comment by webtoolbox** [comment]
Hi Alberto. I'm glad to inform you that we were able to reproduce and fix the issue. The changes are now in Quality Assurance testing. Once it's tested within the next few days, we'll publish the changes to the repository.

**Comment by webtoolbox** [comment]
Hi Alberto. Thanks for your patience while we worked on fixing this issue.

We have made changes to fix the issue in the latest plugin release. To update to the latest version, please follow these steps:

1. Log in to your website's admin control panel.
2. Go to Utilities -> Updates
3. Locate the Website Toolbox Community plugin and click the update button.

Once you've updated the plugin, please confirm and let us know if the issue has been resolved.
