### ISSUE TITLE
Craft 5 Compatibility

### ISSUE THREAD

**Issue by julianfann** [webtoolbox/craftcms-plugin#14]
Is there a plan to support Craft 5? If so, is there a target date for that support?

**Comment by webtoolbox** [comment]
Hi Julian! Thanks for reaching out. Craft 5 is supported. You can use it on Craft 5 now. We'll be updating the plugin to officially mention it as a supported version shortly.

**Comment by webtoolbox** [comment]
Hi Julian! The latest version of our CraftCMS plugin is now live in the CraftCMS plugin store. It officially supports Craft 5. 

Here are the steps to update the plugin:

1. Log in to your website's admin control panel.
2. Navigate to Utilities -> Updates.
3. Find the Website Toolbox Community plugin and click the update button.

**Comment by julianfann** [comment]
@webtoolbox Thanks so much for clarifying!
